service: emailer

provider:
  name: aws
  runtime: nodejs4.3
  stage: production
  region: us-west-2
  profile: mine
  cfLogs: true
  memorySize: 128
  timeout: 5
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Subscribe"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
      Resource: "*"

package:
 exclude:
   - src/**
   - spec/**w
   - package.json
   - serverless.yml
   - .eslintignore
   - .eslintrc
   - .npmignore
   - .serverless/**
   - node_modules/**
 include:
   - transpile-nodejs/*
   - node_modules/aws-sdk/**
   - node_modules/babel-polyfill/**
   - node_modules/mysql/**
   - node_modules/nodemailer/**
   - node_modules/bluebird/**

functions:
  emailer:
    handler: transpile-nodejs/emailer/index.handler
    events:
      - sns: emailer_entrypoint
